Fix modals and removed console.log in AdaptiveResolver
ZationRU/ReactUI pull request #53
Opened 2024-12-20 07:09 UTC by vitiacat

fix: modals uses global close function & removed console.log

2024-12-20 07:13 UTC, levkopo approved these changes

2024-12-31 15:42 UTC, vitiacat commented
- Добавил новый компонент Chip, добавил состояния disabled чекбоксу, слайдеру и радио-кнопке (и исправил отображения состояния disabled свитчу).
- Добавил иконку (а точнее кнопку закрытия) для снекбара и исправил то, что кнопка действия не вызывала onClick
- Наполнил в документации категорию "Selection"

С новым годом, Лева!

2024-12-31 17:02 UTC, levkopo requested changes

2024-12-31 17:02 UTC, levkopo commented on packages/checkbox/package.json
> +  "version": "1.3.1-alpha.0",
Исправь на 1.3.0-alpha.1)

2024-12-31 17:03 UTC, levkopo commented
С новым годом, Витя!

2024-12-31 18:54 UTC, levkopo approved these changes

2024-12-31 18:55 UTC, merged